services:
  backend:
    build: ./server
    container_name: webbuild-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: webbuild-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    env_file:
      - ./server/.env
    restart: unless-stopped